### PR TITLE
FIX pip install fails @ Python 3.11 & Darwin

### LINKED ISSUE #946: pip install fails @ Python 3.11 & Darwin
For some reason dependency is resolved to numpy==1.22.2 instead of numpy==1.26.3

```
$ pip3 install -U --upgrade-strategy eager  opencv-python
Collecting opencv-python
  Using cached opencv-python-4.9.0.80.tar.gz (92.9 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [237 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and platform_system != "Darwin"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Darwin"' don't match your environment
      Collecting cmake>=3.1
        Using cached cmake-3.28.1-py2.py3-none-macosx_10_10_universal2.macosx_10_10_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl.metadata (6.3 kB)
      Collecting numpy==1.22.2
        Using cached numpy-1.22.2.zip (11.4 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting pip
        Using cached pip-23.3.2-py3-none-any.whl.metadata (3.5 kB)
      Collecting scikit-build>=0.14.0
        Using cached scikit_build-0.17.6-py3-none-any.whl.metadata (14 kB)
      Collecting setuptools==59.2.0
        Using cached setuptools-59.2.0-py3-none-any.whl (952 kB)
      Collecting distro (from scikit-build>=0.14.0)
        Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
      Collecting packaging (from scikit-build>=0.14.0)
        Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
      Collecting wheel>=0.32.0 (from scikit-build>=0.14.0)
        Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
      Using cached cmake-3.28.1-py2.py3-none-macosx_10_10_universal2.macosx_10_10_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (48.5 MB)
      Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
      Using cached scikit_build-0.17.6-py3-none-any.whl (84 kB)
      Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
      Using cached distro-1.9.0-py3-none-any.whl (20 kB)
      Using cached packaging-23.2-py3-none-any.whl (53 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (pyproject.toml): started
        Building wheel for numpy (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [187 lines of output]
            setup.py:66: RuntimeWarning: NumPy 1.22.2 may not yet support Python 3.11.
              warnings.warn(
            Running from numpy source directory.
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_philox.pyx
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/mtrand.pyx
            Processing numpy/random/_generator.pyx
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/_common.pyx
            Cythonizing sources
            INFO: blas_opt_info:
            INFO: blas_armpl_info:
            INFO: customize UnixCCompiler
            INFO:   libraries armpl_lp64_mp not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blas_mkl_info:
            INFO:   libraries mkl_rt not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blis_info:
            INFO:   libraries blis not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_info:
            INFO:   libraries openblas not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: accelerate_info:
            INFO:   libraries accelerate not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO: Library accelerate was not found. Ignoring
            INFO:   libraries veclib not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO: Library veclib was not found. Ignoring
            INFO:   FOUND:
            INFO:     extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
            INFO:     extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
            INFO:     define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
            INFO:
            INFO:   FOUND:
            INFO:     extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
            INFO:     extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
            INFO:     define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
            INFO:
            svnversion: error: Failed to locate 'svnversion'.
            svnversion: error: The subversion command line tools are no longer provided by Xcode.
            non-existing path in 'numpy/distutils': 'site.cfg'
            INFO: lapack_opt_info:
            INFO: lapack_armpl_info:
            INFO:   libraries armpl_lp64_mp not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: lapack_mkl_info:
            INFO:   libraries mkl_rt not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_lapack_info:
            INFO:   libraries openblas not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_clapack_info:
            INFO:   libraries openblas,lapack not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: flame_info:
            INFO:   libraries flame not found in ['/Library/Frameworks/Python.framework/Versions/3.11/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO:   FOUND:
            INFO:     extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
            INFO:     extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
            INFO:     define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
            INFO:
            Warning: attempted relative import with no known parent package
            /private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            INFO: build_src
            INFO: building py_modules sources
            creating build
            creating build/src.macosx-10.9-universal2-3.11
            creating build/src.macosx-10.9-universal2-3.11/numpy
            creating build/src.macosx-10.9-universal2-3.11/numpy/distutils
            INFO: building library "npymath" sources
            WARN: Could not locate executable gfortran
            WARN: Could not locate executable f95
            WARN: Could not locate executable nagfor
            WARN: Could not locate executable f90
            WARN: Could not locate executable f77
            WARN: Could not locate executable xlf90
            WARN: Could not locate executable xlf
            WARN: Could not locate executable ifort
            WARN: Could not locate executable ifc
            WARN: Could not locate executable g77
            WARN: Could not locate executable g95
            WARN: Could not locate executable pgfortran
            WARN: don't know how to compile Fortran code on platform 'posix'
            creating build/src.macosx-10.9-universal2-3.11/numpy/core
            creating build/src.macosx-10.9-universal2-3.11/numpy/core/src
            creating build/src.macosx-10.9-universal2-3.11/numpy/core/src/npymath
            INFO: conv_template:> build/src.macosx-10.9-universal2-3.11/numpy/core/src/npymath/npy_math_internal.h
            INFO:   adding 'build/src.macosx-10.9-universal2-3.11/numpy/core/src/npymath' to include_dirs.
            INFO: conv_template:> build/src.macosx-10.9-universal2-3.11/numpy/core/src/npymath/ieee754.c
            INFO: conv_template:> build/src.macosx-10.9-universal2-3.11/numpy/core/src/npymath/npy_math_complex.c
            INFO: None - nothing done with h_files = ['build/src.macosx-10.9-universal2-3.11/numpy/core/src/npymath/npy_math_internal.h']
            INFO: building library "npyrandom" sources
            INFO: building extension "numpy.core._multiarray_tests" sources
            creating build/src.macosx-10.9-universal2-3.11/numpy/core/src/multiarray
            INFO: conv_template:> build/src.macosx-10.9-universal2-3.11/numpy/core/src/multiarray/_multiarray_tests.c
            INFO: building extension "numpy.core._multiarray_umath" sources
            Traceback (most recent call last):
              File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
                self.run_setup()
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
                self).run_setup(setup_script=setup_script)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 461, in <module>
                setup_package()
              File "setup.py", line 453, in setup_package
                setup(**metadata)
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-install-q9rpirls/numpy_6a817671ade44a50af48b19b2a26f13d/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
                       ^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup
                return distutils.core.setup(**attrs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-install-q9rpirls/numpy_6a817671ade44a50af48b19b2a26f13d/numpy/distutils/command/build.py", line 61, in run
                old_build.run(self)
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-build-env-tu2kjzdh/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-install-q9rpirls/numpy_6a817671ade44a50af48b19b2a26f13d/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-install-q9rpirls/numpy_6a817671ade44a50af48b19b2a26f13d/numpy/distutils/command/build_src.py", line 161, in build_sources
                self.build_extension_sources(ext)
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-install-q9rpirls/numpy_6a817671ade44a50af48b19b2a26f13d/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
                sources = self.generate_sources(sources, ext)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-install-q9rpirls/numpy_6a817671ade44a50af48b19b2a26f13d/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-install-q9rpirls/numpy_6a817671ade44a50af48b19b2a26f13d/numpy/core/setup.py", line 456, in generate_config_h
                moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-install-q9rpirls/numpy_6a817671ade44a50af48b19b2a26f13d/numpy/core/setup.py", line 50, in check_types
                out = check_types(*a, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/32/ncl28p2s61l9dqh09kjg31w40000gp/T/pip-install-q9rpirls/numpy_6a817671ade44a50af48b19b2a26f13d/numpy/core/setup.py", line 311, in check_types
                raise SystemError(
            SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

```

### PR DESCRIPTION
**Pull request by ananich**
Fixes https://github.com/opencv/opencv-python/issues/946

### CODE REVIEW

**Comment by jfracon** [comment]
Is there any update on this? I think @ananich commit will solve the issue and also allow working with Python 3.12. Numpy 1.22.2 is not compatible with Python 3.12 due to the deprecation and removal of imp ( AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?)

**Review by jfracon — APPROVED** [review]
This change will allow working with Python 3.12. This is now not possible due to the deprecation and removal of the imp module which is used by Numpy versions below 1.26.0

**Comment by ashlndr** [comment]
I have the same issue on MacOS 10.15.7 and Python 3.12.2. Is there any chance that this fix will be merged?

**Comment by RankoR** [comment]
I guess you would also need to upgrade `setuptools` - for me it works only with the newer `setuptools`.
Currently, I'm doing it in Docker like this:

```
RUN sed -i 's/numpy==1.22.2; python_version>='"'"'3.11'"'"'/numpy>=1.26.3; python_version>='"'"'3.11'"'"'/g' /tmp/opencv-python/pyproject.toml
RUN sed -i 's/setuptools==59.2.0/setuptools==69.5.1/g' /tmp/opencv-python/pyproject.toml
```

At least for me upgrading only numpy didn't work.
