### PR TITLE
Build on Travis CI using manylinux

### PR DESCRIPTION
**Pull request by c-martinez**
This PR should address previous suggestion #1. Builds on Travis seem fine (except for 2.6).

Couple of issues
 - Currently not building for 2.6, because it complains gives `ImportError: cannot import name SkipTest`
 - `build-wheels.sh` will need to be changed in the future:
    - It force-updates `auditwheel` (until the docker image updates auditwheel)
    - It clones `OpenCV` from [my own fork](https://github.com/c-martinez/opencv.git) -- if this is the way forward to build OpenCV wheels, I'll send a PR upstream to incorporate the few changes required.

Is this useful?

### CODE REVIEW

**Comment by skvark** [comment]
Appveyor build file needs minor fix, but otherwise LGTM.

I don't really know the answer to the question if this is the way forward to build OpenCV wheels. If you have a better idea, please share. As the OpenCV maintainers are a bit reluctant to include Python packaging support directly to the main repo (https://github.com/Itseez/opencv/issues/6516), I think this separate repository + cloning OpenCV is pretty much the only option there is.

**Comment by c-martinez** [comment]
Changed the Appveyor build (hopefully it works correctly).

I think you are right and cloning OpenCV to build the wheels might be the only option. I guess what we are missing now is registering the wheels in PyPI. Do you have any experience with it? Otherwise I guess I can figure it out.

**Comment by skvark** [comment]
I have experience running a local PyPI and I can do the uploading. However, there are still a few things to do:

* the builds (cloning) have to be done from the main OpenCV repository
* versioning:
    * do we pull only the latest tag and make builds for it or do we also offer dev builds which are essentially built always when there's a commit in the OpenCV main development branch
* OS X wheels
* Are the Linux wheels allowed in PyPI (at some point they weren't)

I will create separate issues for these.
