### ISSUE TITLE
imdecode Throws an Error

### ISSUE THREAD

**Issue by jsl303** [skvark/opencv-python#218]
Python 3.7.3
opencv-python 4.1.0.25 from pip install opencv-python
The following code returns 
> imdecode_(''): can't read data: OpenCV(4.1.0) /io/opencv/modules/imgcodecs/src/grfmt_webp.cpp:164: error: (-215:Assertio
n failed) data.rows == 1 in function 'readData'                                                                          

```
img = cv2.imread(file)
retval, buf = cv2.imencode(".webp", img, [cv2.IMWRITE_WEBP_QUALITY, 100])
img = cv2.imdecode(buf, 1)
```

However, it works with opencv                    3.4.2 from conda install opencv.

**Comment by jsl303** [comment]
Forgot to mention Kaggle kernel environment (Python 3.6.6 and opencv-python 4.1.0.25) returns None without an error.

**Comment by skvark** [comment]
Looks like the issue is in OpenCV: https://answers.opencv.org/question/210682/cv2-imdecode-webp-format-fails/. The packages have been compiled with webp support. You should open an issue to the OpenCV repository: https://github.com/opencv/opencv

**Comment by jsl303** [comment]
Thanks, just opened one:

https://github.com/opencv/opencv/issues/14978

**Comment by skvark** [comment]
Closing this as the fix depends on upstream. Probably fixed in next release.

**Comment by jsl303** [comment]
It looks like this has been addressed now.
https://github.com/opencv/opencv/pull/14989

**Comment by skvark** [comment]
Yes. It will be included in the next OpenCV version which has not been yet released.

**Comment by jsl303** [comment]
Is there any update? I think 4.1.1 is out? Thanks!

**Comment by skvark** [comment]
I'm currently trying to bump the version to 4.1.1 but there are some issues with 32-bit Linux builds. 4.1.1 will be released after I have fixed them.
