### ISSUE TITLE
OpenCV 3.2 has been released

### ISSUE THREAD

**Issue by virtuald** [skvark/opencv-python#21]
Hopefully updating is just as simple as changing a few numbers in a few places and it will just work. :)

**Comment by skvark** [comment]
Yes, I hope so too but you never know :) 

My plan is to push first new 3.1.0 builds with Python 3.6 support to PyPI (seems that the latest commit builds are now ok) and after that I will update OpenCV to version to 3.2. If everything works fine, I'll release the 3.2.0 builds to PyPI right after that. This is just a very slow process since the builds take a lot of time.

**Comment by skvark** [comment]
Looks like Linux and macOS require some tinkering to get the builds working with 3.2.0.

**Comment by skvark** [comment]
Linux is OK, failures were caused by dropped Python 3.3 support on Numpy side. Pasting macOS errors here for easier access:

````[ 32%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/src/mathfuncs.cpp.o

/Users/travis/build/skvark/opencv-python/opencv/modules/core/src/hal_internal.cpp:111:17: error: no matching function for call to 'sgesv_'

                sgesv_(&m, &n, (float*)a, &lda, piv, (float*)b, &m, info);

                ^~~~~~

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/clapack.h:5571:5: note: candidate function not viable: no known conversion from 'int *' to '__CLPK_integer *' (aka 'long *') for 1st argument

int sgesv_(__CLPK_integer *__n, __CLPK_integer *__nrhs, __CLPK_real *__a,

    ^

/Users/travis/build/skvark/opencv-python/opencv/modules/core/src/hal_internal.cpp:113:17: error: no matching function for call to 'dgesv_'

                dgesv_(&m, &n, (double*)a, &lda, piv, (double*)b, &m, info);

                ^~~~~~

/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/clapack.h:2688:5: note: candidate function not viable: no known conversion from 'int *' to '__CLPK_integer *' (aka 'long *') for 1st argument

int dgesv_(__CLPK_integer *__n, __CLPK_integer *__nrhs, __CLPK_doublereal *__a,

    ^````

It looks like the LAPACK implementation on macOS doesn't except integers as parameters for those functions...

**Comment by skvark** [comment]
3.2.0 builds are now in PyPI. I disabled LAPACK for macOS builds for now.
