### ISSUE TITLE
createThinPlateSplineShapeTransformer missing in 4.0

### ISSUE THREAD

**Issue by starsep** [skvark/opencv-python#177]
### Expected behaviour
It seems that `createThinPlateSplineShapeTransformer` is missing in 4.0
I don't see any differences between https://docs.opencv.org/3.4.5/d1/d85/group__shape.html#ga624261564326d735bc6af7cb4e27bb95
and https://docs.opencv.org/4.0.0/d1/d85/group__shape.html#ga624261564326d735bc6af7cb4e27bb95

### Actual behaviour

```
Traceback (most recent call last):
  File "splines.py", line 2, in <module>
    cv2.createThinPlateSplineShapeTransformer()
AttributeError: module 'cv2.cv2' has no attribute 'createThinPlateSplineShapeTransformer'
```

### Steps to reproduce
`pip install opencv-python==4.0.0.21`
```
import cv2
cv2.createThinPlateSplineShapeTransformer()
```

Works fine with `opencv-python==3.4.5.20`

**Comment by starsep** [comment]
It's caused by moving `shape` module to extra modules in OpenCV.

**Comment by sydney0zq** [comment]
Hi, could you please tell me how to use it again in 4.0? And where the function is moved to?

**Comment by starsep** [comment]
All you need to do is to install package with extra modules.
They have `contrib` in the name: `pip install opencv-contrib-python` or `pip install opencv-contrib-python-headless`.

**Comment by sydney0zq** [comment]
Many thanks for your kind help!

**Comment by ganliqiang** [comment]
thanks  it helps me a lot

**Comment by skvark** [comment]
Please stop spamming.
