### ISSUE TITLE
AttributeError: module 'cv2.text' has no attribute 'TextDetectorCNN'

### ISSUE THREAD

**Issue by starenka** [skvark/opencv-python#915]
### Expected behaviour

the `cv.text.TextDetectorCNN` should exist as the docs https://docs.opencv.org/4.8.0/d1/d66/classcv_1_1text_1_1TextDetectorCNN.html say. I just updated from opencv 4.5 and can't figure out, what's happening. // edit: it seems to still work in `4.7.x`

### Actual behaviour

the class is not in the cv.text module

### Steps to reproduce

```
In [1]: import cv2 as cv

In [2]: cv.__version__
Out[2]: '4.8.1'

In [3]: cv.text.TextDetectorCNN.create
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 cv.text.TextDetectorCNN.create

AttributeError: module 'cv2.text' has no attribute 'TextDetectorCNN'

In [4]: cv.text.TextDetectorCNN_create
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 cv.text.TextDetectorCNN_create
```

##### Issue submission checklist

 - [x] This is not a generic OpenCV usage question (looking for help for coding, other usage questions, homework etc.)
   
 - [x] I have read the README of this repository and understand that this repository provides only an automated build toolchain for OpenCV Python packages (there is no actual OpenCV code here)
   
 - [ ] The issue is related to the build scripts in this repository, to the pre-built binaries or is a feature request (such as "please enable this additional dependency")
 - [x] I'm using the latest version of ``opencv-python``

**Comment by Paulie-Aditya** [comment]
as far as I understand, 
you have to use it as follows:
cv.text.TextDetectorCNN.create(	modelArchFilename, modelWeightsFilename	) ->	retval
cv.text.TextDetectorCNN_create(	modelArchFilename, modelWeightsFilename	) ->	retval

in line 3, you have not used the .create as a function and that is probably why the error has occured


Corrected code: 
import cv2 as cv
 cv.__version__
cv.text.TextDetectorCNN.create(modelArchFilename, modelWeightsFilename) # both modelArchFileName and modelWeightsFilename are required

**Comment by PavloFesenko** [comment]
@starenka, it seems that the module `text` isn't available in the standard `opencv-python` but is available in the extended `opencv-contrib-python` (just tested). 😉

**Comment by starenka** [comment]
i was quite sure i had that one installed too, cause i've used it before
bumping the package. will doublecheck tho. thanks

--
'aknerats'[::-1]

**Comment by starenka** [comment]
> @starenka, it seems that the module `text` isn't available in the standard `opencv-python` but is available in the extended `opencv-contrib-python` (just tested). 😉

i had opencv-contrib installed, when i was creating the issue, doublechecked now...

```
In [1]: import cv2 as cv

In [2]: cv.text.TextDetectorCNN_create
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 cv.text.TextDetectorCNN_create

AttributeError: module 'cv2.text' has no attribute 'TextDetectorCNN_create'

In [3]: cv.text.TextDetectorCNN
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 cv.text.TextDetectorCNN

AttributeError: module 'cv2.text' has no attribute 'TextDetectorCNN'

In [4]: !pip list | grep opencv
opencv-contrib-python    4.8.1.78
opencv-python            4.8.1.78
```

it works okay on `4.7`


```
In [1]: import cv2 as cv

In [2]: cv.text.TextDetectorCNN_create
Out[2]: <function TextDetectorCNN_create>

In [3]: cv.text.TextDetectorCNN
Out[3]: cv2.text.TextDetectorCNN

In [4]: !pip list | grep opencv
opencv-contrib-python    4.7.0.72
opencv-python            4.7.0.72
```

**Comment by PavloFesenko** [comment]
@starenka, you shouldn't install `opencv-python` and `opencv-contrib-python` in the same environment. Create a new clean environment, install `opencv-contrib-python` and it will work.

**Comment by starenka** [comment]
what? i'm using it like this literally for years... this is news to me then

**Comment by PavloFesenko** [comment]
@starenka, it is clearly mentioned on the [README page](https://github.com/opencv/opencv-python): 😉

> There are four different packages (see options 1, 2, 3 and 4 below) and you should SELECT ONLY ONE OF THEM. Do not install multiple different packages in the same environment. There is no plugin architecture: all the packages use the same namespace (cv2). If you installed multiple different packages in the same environment, uninstall them all with pip uninstall and reinstall only one package.
> 
> a. Packages for standard desktop environments (Windows, macOS, almost any GNU/Linux distribution)
> 
> Option 1 - Main modules package: pip install opencv-python
> Option 2 - Full package (contains both main modules and contrib/extra modules): pip install opencv-contrib-python (check contrib/extra modules listing from [OpenCV documentation](https://docs.opencv.org/master/))
>
> b. Packages for server (headless) environments (such as Docker, cloud environments etc.), no GUI library dependencies
> 
> These packages are smaller than the two other packages above because they do not contain any GUI functionality (not compiled with Qt / other GUI components). This means that the packages avoid a heavy dependency chain to X11 libraries and you will have for example smaller Docker images as a result. You should always use these packages if you do not use cv2.imshow et al. or you are using some other package (such as PyQt) than OpenCV to create your GUI.
> 
> Option 3 - Headless main modules package: pip install opencv-python-headless
> Option 4 - Headless full package (contains both main modules and contrib/extra modules): pip install opencv-contrib-python-headless (check contrib/extra modules listing from [OpenCV documentation](https://docs.opencv.org/master/))

**Comment by starenka** [comment]
:facepalm: 

funny it worked for me since 3.x :) sorry, @PavloFesenko
